apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app2
  namespace: default
  labels:
    app: redis-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app2
  template:
    metadata:
      labels:
        app: redis-app2
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"