apiVersion: v1
kind: Service
metadata:
  name: redis-app2-service
  namespace: default
  labels:
    app: redis-app2
spec:
  selector:
    app: redis-app2
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP